# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBBIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katakunci', models.TextField()),
            ],
            options={
                'db_table': 'datakata',
                'verbose_name_plural': 'Data KBBI',
            },
        ),
    ]
